source 'https://github.com/CocoaPods/Specs.git'

target 'CMSwitchView', :exclusive => true do
  pod "CMSwitchView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CMSwitchView", :path => "../"

  
end
